#!/usr/bin/env python
import sys
import time
from pathlib import Path

from globals import Variables
from arguments import get_arguments
from helpers import get_video_duration, pause, cleanup
from mute_detect import get_muted_sections, get_sounded_sections, audio_summary
from status_thread import StatusPrinter
from workers import start_work
from concat import concat_prepare_list, concat

def main():
    vars = Variables()

    vars.args = get_arguments()
    vars.program_start_time = time.time()
    vars.input_file_path = Path(vars.args.filename)
    vars.input_file_name = vars.input_file_path.stem
    vars.input_file_extension = vars.input_file_path.suffix
    vars.input_full_file_path = vars.input_file_path.absolute()
    vars.output_file_name = vars.args.output or f"{vars.input_file_name} (cut){vars.input_file_extension}"
    vars.temp_extension = ".mkv" if vars.args.copy else ".mp4"

    vars.total_duration = get_video_duration(vars.input_full_file_path)

    get_muted_sections(vars)
    get_sounded_sections(vars)
    audio_summary(vars)
    pause(vars.args.pause, "Press Enter to start processing...")

    status = StatusPrinter(vars)
    if not vars.args.verbose and not vars.args.very_verbose:
        status.start()

    start_work(vars, status)

    if not vars.args.verbose and not vars.args.very_verbose:
        status.stop()

    concat_prepare_list(vars)
    sys.stdout.write(f"Failed conversions: {vars.failed_conversions}\n")
    sys.stdout.flush()

    pause(vars.args.pause, "Press Enter to concat videos...")
    concat(vars)
    pause(vars.args.pause, "Press Enter to clean up temporary files...")
    cleanup(vars)
    sys.stdout.write(f"Took: {time.time() - vars.program_start_time:.2f}\n")
    sys.stdout.flush()



if __name__ == "__main__":
    main()
